# Use OpenJDK 11 as the base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the jar file to the container
COPY target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

# Expose the port on which the Spring Boot app will run
EXPOSE 8080

# Command to run the Spring Boot application
CMD ["java", "-jar", "demo.jar"]
